AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
